# File: netlify.toml
# OOOSH Driver Verification - Netlify Configuration
# Replace your existing netlify.toml with this content

[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers with proper CSP for Tailwind CSS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://ivs.idenfy.com; style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://ivs.idenfy.com https://api.claude.ai https://script.google.com https://script.googleusercontent.com; frame-src https://ivs.idenfy.com;"

# Function-specific configuration (if needed)
[functions]
  directory = "netlify/functions"
