# File: netlify.toml
# OOOSH Driver Verification - Netlify Configuration
# Fixed version with no hardcoded Idenfy URLs

[build]
  publish = "build"
  command = "npm run build"
  command = "npm install && apt-get update && apt-get install -y poppler-utils && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers with CSP that doesn't expose Idenfy URLs
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.claude.ai https://script.google.com https://script.googleusercontent.com https:; frame-src https:;"

# Function-specific configuration - use root functions directory
[functions]
  directory = "functions"
